export const INCOMPLETE = 'incomplete'
export const COMPLETED = 'completed'
export const EXPIRED = 'expired'
export const TODAY = 'today'
export const EXPIRE_DATETIME = 'expire_datetime'
export const URGENCY = 'urgency'
export const CREATE_DATETIME = 'create_datetime'