export const ALL = 'all'
export const INCOMPLETE = 'incomplete'
export const COMPLETED = 'completed'
export const EXPIRED = 'expired'
export const CREATE = 'create'
export const UPDATE = 'update'
export const HIDDEN = 'hidden'